name: Drivah
description: Buildkite plugin to wrap around drivah for building, pushing, and tagging docker images.
#TODO change to elastic
author: https://github.com/jmpavlec
requirements:
  - vault
  - drivah
  - buildah
configuration:
  properties:
    dockerfile_path:
      type: string
      description: The full path from the base of the repo to the directory containing the Dockerfile
    docker_login_username:
      type: string
      description: The username to log into docker with
    vault_secret_path:
      type: string
      description: The vault path to get the secrets for the docker registry login
    build_only:
      type: boolean
      description: Only build the docker image, don't push it
    include_sub_directories:
      type: boolean
      default: false
      description: Build all combinations of Dockerfile and drivah.toml from the `dockerfile_path` dir and below.
    drivah_debug:
      type: boolean
      default: false
      description: Toggle on debug for the drivah build
  required: ['dockerfile_path', 'docker_login_username', 'vault_secret_path']
